apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teams-api
  namespace: wc2026
  annotations:
    cert-manager.io/issuer: "api-prod-cert-issuer" #should match the issuer defined on root ingress-nginx TLS config
    nginx.ingress.kubernetes.io/enable-cors: "true" #allow any host
spec:
  rules:
    - host: api.wc2026.motojoapps.com
      http:
        paths:
          - backend:
              service:
                name: players-api
                port:
                  name: http
            path: /teams
            pathType: Prefix
  ingressClassName: nginx
